CREATE TABLE TB_CLIENTE(
    ID_TB_CLIENTE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME_TB_CLIENTE VARCHAR(50) NOT NULL,
    SOBRENOME_TB_CLIENTE VARCHAR(60) NOT NULL,
    TELEFONE_TB_CLIENTE VARCHAR(14) NOT NULL,
    EMAIL_TB_CLIENTE VARCHAR(256) NOT NULL
);

CREATE TABLE TB_LIVRO(
    ID_TB_LIVRO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TITULO_TB_LIVRO VARCHAR(200) NOT NULL,
    AUTOR_TB_LIVRO VARCHAR(50) NOT NULL,
    EDITORA_TB_LIVRO VARCHAR(100) NOT NULL,
    ANO_TB_LIVRO CHAR(4),
    CATEGORIA_TB_LIVRO VARCHAR(160) NOT NULL
);

CREATE TABLE TB_RESERVA(
    ID_TB_RESERVA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ID_TB_CLIENTE INTEGER NOT NULL,
    ID_TB_LIVRO INTEGER NOT NULL,
    DATA_RESERVA_TB_RESERVA DATE NOT NULL,
    DATA_PRAZO_TB_RESERVA DATE NOT NULL,
    STATUS_TB_RESERVA BOOLEAN NOT NULL,
    FOREIGN KEY (ID_TB_CLIENTE) REFERENCES TB_CLIENTE(ID_TB_CLIENTE),
    FOREIGN KEY (ID_TB_LIVRO) REFERENCES TB_LIVRO(ID_TB_LIVRO)
);


-- SOLI DEO GLORIA! 